#!/usr/bin/env node
/**
 * Generates TypeScript types from the Rust `types` crate.
 *
 * The Rust `types` crate is the single source of truth for the Tauri/JS
 * boundary DTOs. This script parses the `pub struct`/`pub enum` definitions in
 * `src-tauri/libs/types/src/*.rs` and emits a TypeScript module with matching
 * interfaces/enums (camelCase field names, matching the `#[serde(rename_all =
 * "camelCase")]` attribute).
 *
 * Usage: `node scripts/gen-types.mjs`
 * Output: `src/lib/generated/types.ts`
 *
 * The generated file is committed; CI verifies it is in sync (see
 * `scripts/check-types-sync.mjs`).
 */

import { readFile, readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const TYPES_DIR = join(__dirname, "..", "src-tauri", "libs", "types", "src");
const OUT_FILE = process.env.GEN_TYPES_OUT ?? join(__dirname, "..", "src", "lib", "generated", "types.ts");

// Rust primitive -> TS type.
const PRIMITIVES = {
  String: "string",
  bool: "boolean",
  u8: "number",
  u16: "number",
  u32: "number",
  u64: "number",
  i8: "number",
  i16: "number",
  i32: "number",
  i64: "number",
  f32: "number",
  f64: "number",
};

// Rust type expression -> TS type expression.
function rustTypeToTs(typeExpr, knownTypes) {
  const t = typeExpr.trim();

  if (PRIMITIVES[t]) {
    return PRIMITIVES[t];
  }

  // Option<T> -> T | null
  const optionMatch = t.match(/^Option<(.+)>$/);
  if (optionMatch) {
    return `${rustTypeToTs(optionMatch[1], knownTypes)} | null`;
  }

  // Vec<T> -> T[]
  const vecMatch = t.match(/^Vec<(.+)>$/);
  if (vecMatch) {
    return `${rustTypeToTs(vecMatch[1], knownTypes)}[]`;
  }

  // [T; N] -> T[] (fixed-size array)
  const arrayMatch = t.match(/^\[(.+);\s*\d+\]$/);
  if (arrayMatch) {
    return `${rustTypeToTs(arrayMatch[1], knownTypes)}[]`;
  }

  // crate::chat::MatrixChatMessage -> MatrixChatMessage
  const crateMatch = t.match(/^crate::[a-z_]+::(.+)$/);
  if (crateMatch) {
    return crateMatch[1];
  }

  // Known named type (enum/struct defined in the crate).
  if (knownTypes.has(t)) {
    return t;
  }

  // Fallback: strip any remaining generic/namespace wrappers.
  return t;
}

// Convert snake_case to camelCase.
function toCamelCase(name) {
  return name.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

// Convert a Rust enum variant name (PascalCase) to a TS string literal
// (lowerCamelCase), matching serde's default enum variant serialization.
function enumVariantToLiteral(name) {
  const camel = toCamelCase(name);
  return camel.charAt(0).toLowerCase() + camel.slice(1);
}

// Parse a single `pub struct` or `pub enum` block from source text.
function parseTypeBlock(source) {
  const blocks = [];
  const regex = /pub\s+(?:struct|enum)\s+(\w+)\s*\{([\s\S]*?)\n\}/g;
  let match;
  while ((match = regex.exec(source)) !== null) {
    // Look backwards from the `pub` keyword for the derive attribute line.
    const before = source.slice(0, match.index);
    const deriveMatch = before.match(/#\[derive\(([^\]]+)\)\]\s*$/m);
    const derives = deriveMatch ? deriveMatch[1] : "";
    blocks.push({
      name: match[1],
      kind: match[0].includes("enum") ? "enum" : "struct",
      body: match[2],
      isDeserialize: derives.includes("Deserialize"),
    });
  }
  return blocks;
}

// Parse struct fields: `pub name: Type,` (skipping serde attribute lines).
function parseStructFields(body) {
  const fields = [];
  const fieldRegex = /^\s*pub\s+(\w+)\s*:\s*([^,]+),?\s*$/gm;
  let match;
  while ((match = fieldRegex.exec(body)) !== null) {
    fields.push({ name: match[1], type: match[2].trim() });
  }
  return fields;
}

// Parse enum variants: `    VariantName,` (skipping doc comments and serde attrs).
function parseEnumVariants(body) {
  const variants = [];
  const variantRegex = /^\s*([A-Z][A-Za-z0-9]*)\s*,\s*$/gm;
  let match;
  while ((match = variantRegex.exec(body)) !== null) {
    variants.push(match[1]);
  }
  return variants;
}

// Whether a Rust type expression is an `Option<...>`.
function isOptionType(typeExpr) {
  return /^Option<.+>$/.test(typeExpr.trim());
}

async function main() {
  const files = (await readdir(TYPES_DIR)).filter((f) => f.endsWith(".rs"));
  const allBlocks = [];
  const knownTypes = new Set();

  for (const file of files) {
    const source = await readFile(join(TYPES_DIR, file), "utf8");
    const blocks = parseTypeBlock(source);
    for (const block of blocks) {
      knownTypes.add(block.name);
    }
    allBlocks.push(...blocks.map((b) => ({ ...b, file })));
  }

  const lines = [
    "// AUTO-GENERATED by scripts/gen-types.mjs — do not edit by hand.",
    "// Source of truth: src-tauri/libs/types/src/*.rs",
    "// Regenerate with: node scripts/gen-types.mjs",
    "",
  ];

  for (const block of allBlocks) {
    if (block.kind === "enum") {
      const variants = parseEnumVariants(block.body);
      const literals = variants.map(enumVariantToLiteral).map((v) => `"${v}"`);
      lines.push(`export type ${block.name} = ${literals.join(" | ")};`);
      lines.push("");
    } else {
      const fields = parseStructFields(block.body);
      lines.push(`export interface ${block.name} {`);
      for (const field of fields) {
        const tsType = rustTypeToTs(field.type, knownTypes);
        // `Option<T>` fields are optional in TS (serde omits them when None).
        // `#[serde(default)]` fields are always present in serialized output,
        // so they stay required.
        const optional = isOptionType(field.type) ? "?" : "";
        lines.push(`  ${toCamelCase(field.name)}${optional}: ${tsType};`);
      }
      lines.push("}");
      lines.push("");
    }
  }

  const output = lines.join("\n");
  await writeFile(OUT_FILE, output, "utf8");
  console.log(`Generated ${OUT_FILE} (${allBlocks.length} types)`);
}

main().catch((error) => {
  console.error("Failed to generate types:", error);
  process.exit(1);
});