pub const CALLBACK_REDIRECT_URI: &str = "http://127.0.0.1:8743/matrix-oauth-callback";
pub const TOKEN_ROTATION_INTERVAL_SECONDS: u64 = 30 * 60;
pub const SYNC_TIMEOUT_SECONDS: u64 = 15;
pub const LONG_POLL_SYNC_TIMEOUT_SECONDS: u64 = 25;
pub const WORKER_UNAUTH_SLEEP_SECONDS: u64 = 2;
pub const WORKER_RETRY_INITIAL_DELAY_MS: u64 = 500;
pub const WORKER_RETRY_MAX_DELAY_MS: u64 = 15_000;
