name: 'publish'

on:
  push:
    branches:
      - master

jobs:
  cargo-fmt:
    uses: ./.github/workflows/quality-checks.yml
    with:
      check: cargo-fmt

  cargo-clippy:
    uses: ./.github/workflows/quality-checks.yml
    with:
      check: cargo-clippy

  pnpm-check:
    uses: ./.github/workflows/quality-checks.yml
    with:
      check: pnpm-check

  publish-tauri:
    needs:
      - cargo-fmt
      - cargo-clippy
      - pnpm-check
    uses: ./.github/workflows/build-tauri-job.yml
    with:
      platform: 'macos-latest'
      args: '--target aarch64-apple-darwin'
      rust-targets: 'aarch64-apple-darwin'
      artifact-name: 'singularity-macos-aarch64'
      artifact-path: 'src-tauri/target/aarch64-apple-darwin/release/bundle/**'
    secrets: inherit

  publish-tauri-linux:
    needs:
      - cargo-fmt
      - cargo-clippy
      - pnpm-check
    uses: ./.github/workflows/build-tauri-job.yml
    with:
      platform: 'ubuntu-22.04'
      args: ''
      rust-targets: ''
      artifact-name: 'singularity-linux-x64'
      artifact-path: |
        src-tauri/target/release/bundle/**/*.deb
        src-tauri/target/release/bundle/**/*.AppImage
        src-tauri/target/release/bundle/**/*.rpm
    secrets: inherit

  publish-tauri-windows:
    needs:
      - cargo-fmt
      - cargo-clippy
      - pnpm-check
    uses: ./.github/workflows/build-tauri-job.yml
    with:
      platform: 'windows-latest'
      args: ''
      rust-targets: ''
      artifact-name: 'singularity-windows-x64'
      artifact-path: 'src-tauri/target/release/bundle/**'
    secrets: inherit

  publish-flatpak:
    needs:
      - cargo-fmt
      - cargo-clippy
      - pnpm-check
    uses: ./.github/workflows/build-flatpak-job.yml
    with:
      manifest-path: 'flatpak/io.github.singularity.Singularity.yml'
      bundle-name: 'singularity-linux-flatpak.flatpak'
      artifact-name: 'singularity-linux-flatpak'
    secrets: inherit
